In [3]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import pandas as pd

In [4]:
test_df = pd.DataFrame({
    "A": [10, 20, 30, 40, 55, 60, 80],
    "B": [40, 50, 60, 90, 34, 20, 60],
    "C": [35, 40, 70, 56, 49, 30, 70],
    "D": [30, 50, 75, 50, 40, 29, 70],
    "E": [40, 70, 65, 60, 50, 40, 80]
})


In [10]:
batch_size = 32
num_samples = len(test_df)
num_samples

7

In [11]:
indices = np.arange(num_samples)
indices

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
int(np.ceil(num_samples / batch_size))

1

In [24]:
class Numbers:
    def __len__(self):
        return 0

    def __getitem__(self, idx):
        return idx * 5


In [25]:
nums = Numbers()
len(nums)        # → 5

0

In [26]:
nums[0]          # → 0

0

In [27]:
nums[1]          # → 10

5

In [28]:
nums[4]          # → 40

20

In [40]:
np.random.seed(42)

(np.random.rand(3))

array([0.37454012, 0.95071431, 0.73199394])

In [36]:
(np.random.rand(3))

array([0.37454012, 0.95071431, 0.73199394])

In [32]:
(np.random.rand(3))

array([0.59865848, 0.15601864, 0.15599452])

In [33]:
(np.random.rand(3))

array([0.05808361, 0.86617615, 0.60111501])

In [41]:
img_size = (224, 224)

In [46]:
input_shape = (img_size, 3)

In [45]:
input_shape

(224, 224, 3)