In [2]:
import torch
import numpy as np

In [4]:
t1 = torch.tensor([1,2,3,4,5])
t1

tensor([1, 2, 3, 4, 5])

In [5]:
t1.shape

torch.Size([5])

In [7]:
t2 = torch.tensor([[1,2,3,4,5], [1,2,3,4,5]])
t2

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [8]:
t2.shape

torch.Size([2, 5])

In [12]:
t3 = torch.tensor([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
t3

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [13]:
t3.shape

torch.Size([3, 5])

In [9]:
n1 = np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [10]:
n1.shape

(5,)

In [11]:
n2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
n2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [14]:
t_zero = torch.zeros(5)
t_zero

tensor([0., 0., 0., 0., 0.])

In [15]:
t1_zero = torch.zeros(3,5)
t1_zero

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [16]:
n_zero = np.zeros(5)
n_zero

array([0., 0., 0., 0., 0.])

In [18]:
n1_zero = np.zeros([3,5])
n1_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
lls = np.linspace(0.01, 0.99, 99)
lls

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [3]:
results = {"predictions":{}}
results["predictions"]["quality"] = {"risk_score": 14, "risk_level": 50}
results

{'predictions': {'quality': {'risk_score': 14, 'risk_level': 50}}}

In [5]:
import pandas as pd
df = pd.DataFrame({"A": [2 ,23, 34, 45], "B": [3, 30, 40, 50], "C": [5, 55, 65, 75]})

In [6]:
df

A   B   C
0   2   3   5
1  23  30  55
2  34  40  65
3  45  50  75

In [11]:
for idx, row in df.iterrows():
    print("row index", idx, "row content", row)

row index 0 row content A    2
B    3
C    5
Name: 0, dtype: int64
row index 1 row content A    23
B    30
C    55
Name: 1, dtype: int64
row index 2 row content A    34
B    40
C    65
Name: 2, dtype: int64
row index 3 row content A    45
B    50
C    75
Name: 3, dtype: int64


In [13]:
for key, value in df.items():
    print("key", key, "value", value)

key A value 0     2
1    23
2    34
3    45
Name: A, dtype: int64
key B value 0     3
1    30
2    40
3    50
Name: B, dtype: int64
key C value 0     5
1    55
2    65
3    75
Name: C, dtype: int64


In [14]:
report = []
report.append("="*80)
report.append("E-COMMERCE QUALITY CONTROL ANALYSIS REPORT")
report.append("="*80)
report

['================================================================================',
 'E-COMMERCE QUALITY CONTROL ANALYSIS REPORT',
 '================================================================================']

In [16]:
report_str = "\n".join(report)
report_str

'================================================================================\nE-COMMERCE QUALITY CONTROL ANALYSIS REPORT\n================================================================================'

In [17]:
SERVICES = {
    "quality_predictor": {
        "url": "http://localhost:8001",
        "enabled": True,
        "timeout": 30
    },
    "delivery_predictor": {
        "url": "http://localhost:8002",
        "enabled": True,
        "timeout": 30
    },
    "image_classifier": {
        "url": "http://localhost:8003",
        "enabled": True,
        "timeout": 60                    # Longer for image processing
    },
    "object_detector": {
        "url": "http://localhost:8004",
        "enabled": True,
        "timeout": 60  
    }
}

In [23]:
pred = SERVICES.get("quality_predictor")
pred["url"]

'http://localhost:8001'